// ===== СЛОВА ДЛЯ ИГРЫ "КРОКОДИЛ" =====

const crocodileWords = {
    objects: [
{ word: 'Телефон', difficulty: 'easy', category: 'objects' },
        { word: 'Книга', difficulty: 'easy', category: 'objects' },
        { word: 'Стул', difficulty: 'easy', category: 'objects' },
        { word: 'Лампа', difficulty: 'easy', category: 'objects' },
        { word: 'Часы', difficulty: 'easy', category: 'objects' },
        { word: 'Очки', difficulty: 'easy', category: 'objects' },
        { word: 'Ключи', difficulty: 'easy', category: 'objects' },
        { word: 'Рюкзак', difficulty: 'easy', category: 'objects' },
        { word: 'Зонт', difficulty: 'medium', category: 'objects' },
        { word: 'Микрофон', difficulty: 'medium', category: 'objects' },
        { word: 'Ноутбук', difficulty: 'easy', category: 'objects' },
        { word: 'Холодильник', difficulty: 'easy', category: 'objects' },
        { word: 'Телевизор', difficulty: 'easy', category: 'objects' },
        { word: 'Кровать', difficulty: 'easy', category: 'objects' },
        { word: 'Зеркало', difficulty: 'easy', category: 'objects' },
        { word: 'Вилка', difficulty: 'easy', category: 'objects' },
        { word: 'Ложка', difficulty: 'easy', category: 'objects' },
        { word: 'Нож', difficulty: 'easy', category: 'objects' },
        { word: 'Тарелка', difficulty: 'easy', category: 'objects' },
        { word: 'Чашка', difficulty: 'easy', category: 'objects' },
        { word: 'Молоток', difficulty: 'medium', category: 'objects' },
        { word: 'Отвёртка', difficulty: 'medium', category: 'objects' },
        { word: 'Пила', difficulty: 'medium', category: 'objects' },
        { word: 'Дрель', difficulty: 'medium', category: 'objects' },
        { word: 'Наушники', difficulty: 'easy', category: 'objects' },
        { word: 'Планшет', difficulty: 'easy', category: 'objects' },
        { word: 'Калькулятор', difficulty: 'easy', category: 'objects' },
        { word: 'Флешка', difficulty: 'medium', category: 'objects' },
        { word: 'Клавиатура', difficulty: 'medium', category: 'objects' },
        { word: 'Мышь', difficulty: 'medium', category: 'objects' }, // компьютерная
        { word: 'Утюг', difficulty: 'easy', category: 'objects' },
        { word: 'Стиральная машина', difficulty: 'medium', category: 'objects' },
        { word: 'Пылесос', difficulty: 'medium', category: 'objects' },
        { word: 'Батарейка', difficulty: 'easy', category: 'objects' },
        { word: 'Лампочка', difficulty: 'easy', category: 'objects' },
        { word: 'Кубик Рубика', difficulty: 'medium', category: 'objects' },
        { word: 'Гитара', difficulty: 'medium', category: 'objects' },
        { word: 'Пианино', difficulty: 'medium', category: 'objects' },
        { word: 'Барабан', difficulty: 'medium', category: 'objects' },
        { word: 'Шарф', difficulty: 'easy', category: 'objects' },
        { word: 'Шапка', difficulty: 'easy', category: 'objects' },
        { word: 'Перчатки', difficulty: 'easy', category: 'objects' },
        { word: 'Ремень', difficulty: 'medium', category: 'objects' },
        { word: 'Галстук', difficulty: 'medium', category: 'objects' },
        { word: 'Кошелёк', difficulty: 'easy', category: 'objects' },
        { word: 'Сумочка', difficulty: 'easy', category: 'objects' },
        { word: 'Бинокль', difficulty: 'medium', category: 'objects' },
        { word: 'Компас', difficulty: 'medium', category: 'objects' },
        { word: 'Термос', difficulty: 'medium', category: 'objects' },
        { word: 'Фонарик', difficulty: 'easy', category: 'objects' },
        { word: 'Ножницы', difficulty: 'easy', category: 'objects' },
        { word: 'Линейка', difficulty: 'easy', category: 'objects' },
        { word: 'Скотч', difficulty: 'medium', category: 'objects' },
        { word: 'Клей', difficulty: 'medium', category: 'objects' },
        { word: 'Кран', difficulty: 'medium', category: 'objects' },
        { word: 'Дверь', difficulty: 'easy', category: 'objects' },
        { word: 'Окно', difficulty: 'easy', category: 'objects' },
        { word: 'Ковёр', difficulty: 'medium', category: 'objects' },
        { word: 'Штора', difficulty: 'medium', category: 'objects' },
        { word: 'Ваза', difficulty: 'easy', category: 'objects' },
        { word: 'Картина', difficulty: 'medium', category: 'objects' },
        { word: 'Рамка', difficulty: 'medium', category: 'objects' },
        { word: 'Будильник', difficulty: 'medium', category: 'objects' },
        { word: 'Зарядка', difficulty: 'medium', category: 'objects' },
        { word: 'Акварель', difficulty: 'medium', category: 'objects' },
        { word: 'Оригами', difficulty: 'medium', category: 'objects' },
        { word: 'Матрёшка', difficulty: 'medium', category: 'objects' },
        { word: 'Хот-дог', difficulty: 'medium', category: 'objects' },
        { word: 'Стиральная машина', difficulty: 'hard', category: 'objects' },
    { word: 'Микроволновая печь', difficulty: 'hard', category: 'objects' },
    { word: 'Электрочайник', difficulty: 'hard', category: 'objects' },
    { word: 'Кофеварка', difficulty: 'hard', category: 'objects' },
    { word: 'Блендер', difficulty: 'hard', category: 'objects' },
    { word: 'Тостер', difficulty: 'hard', category: 'objects' },
    { word: 'Мультиварка', difficulty: 'hard', category: 'objects' },
    { word: 'Пароочиститель', difficulty: 'hard', category: 'objects' },
    { word: 'Кубик Рубика', difficulty: 'hard', category: 'objects' }, // уже был medium, можно поднять
    { word: 'Секундомер', difficulty: 'hard', category: 'objects' },
    { word: 'Термометр', difficulty: 'hard', category: 'objects' },
    { word: 'Манекен', difficulty: 'hard', category: 'objects' },
    { word: 'Калейдоскоп', difficulty: 'hard', category: 'objects' },
    { word: 'Телескоп', difficulty: 'hard', category: 'objects' },
    { word: 'Микроскоп', difficulty: 'hard', category: 'objects' }
    ],
    
    animals: [
{ word: 'Кошка', difficulty: 'easy', category: 'animals' },
        { word: 'Собака', difficulty: 'easy', category: 'animals' },
        { word: 'Лошадь', difficulty: 'easy', category: 'animals' },
        { word: 'Корова', difficulty: 'easy', category: 'animals' },
        { word: 'Слон', difficulty: 'easy', category: 'animals' },
        { word: 'Лев', difficulty: 'easy', category: 'animals' },
        { word: 'Пингвин', difficulty: 'medium', category: 'animals' },
        { word: 'Кенгуру', difficulty: 'medium', category: 'animals' },
        { word: 'Дельфин', difficulty: 'medium', category: 'animals' },
        { word: 'Бегемот', difficulty: 'medium', category: 'animals' },
        { word: 'Жираф', difficulty: 'easy', category: 'animals' },
        { word: 'Зебра', difficulty: 'easy', category: 'animals' },
        { word: 'Обезьяна', difficulty: 'easy', category: 'animals' },
        { word: 'Медведь', difficulty: 'easy', category: 'animals' },
        { word: 'Волк', difficulty: 'easy', category: 'animals' },
        { word: 'Лиса', difficulty: 'easy', category: 'animals' },
        { word: 'Енот', difficulty: 'medium', category: 'animals' },
        { word: 'Осьминог', difficulty: 'medium', category: 'animals' },
        { word: 'Акула', difficulty: 'medium', category: 'animals' },
        { word: 'Кит', difficulty: 'medium', category: 'animals' },
        { word: 'Панда', difficulty: 'easy', category: 'animals' },
        { word: 'Тигр', difficulty: 'easy', category: 'animals' },
        { word: 'Крокодил', difficulty: 'medium', category: 'animals' },
        { word: 'Страус', difficulty: 'medium', category: 'animals' },
        { word: 'Павлин', difficulty: 'medium', category: 'animals' },
        { word: 'Попугай', difficulty: 'easy', category: 'animals' },
        { word: 'Хамелеон', difficulty: 'medium', category: 'animals' },
        { word: 'Улитка', difficulty: 'medium', category: 'animals' },
        { word: 'Паук', difficulty: 'medium', category: 'animals' },
        { word: 'Бабочка', difficulty: 'easy', category: 'animals' },
        { word: 'Платипус', difficulty: 'hard', category: 'animals' },
    { word: 'Ехидна', difficulty: 'hard', category: 'animals' },
    { word: 'Аксолотль', difficulty: 'hard', category: 'animals' },
    { word: 'Нарвал', difficulty: 'hard', category: 'animals' },
    { word: 'Тарсиер', difficulty: 'hard', category: 'animals' },
    { word: 'Манул', difficulty: 'hard', category: 'animals' },
    { word: 'Окапи', difficulty: 'hard', category: 'animals' },
    { word: 'Фенек', difficulty: 'hard', category: 'animals' },
    { word: 'Ленивец', difficulty: 'hard', category: 'animals' },
    { word: 'Муравьед', difficulty: 'hard', category: 'animals' },
    { word: 'Броненосец', difficulty: 'hard', category: 'animals' },
    { word: 'Капибара', difficulty: 'hard', category: 'animals' }
    ],
    
    actions: [
{ word: 'Бегать', difficulty: 'easy', category: 'actions' },
        { word: 'Прыгать', difficulty: 'easy', category: 'actions' },
        { word: 'Плавать', difficulty: 'easy', category: 'actions' },
        { word: 'Танцевать', difficulty: 'easy', category: 'actions' },
        { word: 'Спать', difficulty: 'easy', category: 'actions' },
        { word: 'Есть', difficulty: 'easy', category: 'actions' },
        { word: 'Пить', difficulty: 'easy', category: 'actions' },
        { word: 'Готовить', difficulty: 'medium', category: 'actions' },
        { word: 'Водить машину', difficulty: 'medium', category: 'actions' },
        { word: 'Читать', difficulty: 'medium', category: 'actions' },
        { word: 'Петь', difficulty: 'easy', category: 'actions' },
        { word: 'Рисовать', difficulty: 'easy', category: 'actions' },
        { word: 'Писать', difficulty: 'easy', category: 'actions' },
        { word: 'Смеяться', difficulty: 'easy', category: 'actions' },
        { word: 'Плакать', difficulty: 'easy', category: 'actions' },
        { word: 'Обнимать', difficulty: 'easy', category: 'actions' },
        { word: 'Целовать', difficulty: 'medium', category: 'actions' },
        { word: 'Бить', difficulty: 'medium', category: 'actions' },
        { word: 'Летать', difficulty: 'medium', category: 'actions' },
        { word: 'Копать', difficulty: 'medium', category: 'actions' },
        { word: 'Рыбачить', difficulty: 'medium', category: 'actions' },
        { word: 'Кататься на лыжах', difficulty: 'medium', category: 'actions' },
        { word: 'Йога', difficulty: 'medium', category: 'actions' },
        { word: 'Селфи делать', difficulty: 'medium', category: 'actions' },
        { word: 'Зевать', difficulty: 'easy', category: 'actions' },
        { word: 'Чихать', difficulty: 'easy', category: 'actions' },
        { word: 'Кашлять', difficulty: 'easy', category: 'actions' },
        { word: 'Зевать', difficulty: 'hard', category: 'actions' }, // легко, но если добавить "одновременно жевать жвачку"
    { word: 'Чихать с открытыми глазами', difficulty: 'hard', category: 'actions' },
    { word: 'Икать и петь', difficulty: 'hard', category: 'actions' },
    { word: 'Жонглировать тремя мячами', difficulty: 'hard', category: 'actions' },
    { word: 'Делать сальто назад', difficulty: 'hard', category: 'actions' },
    { word: 'Имитировать оргазм', difficulty: 'hard', category: 'actions' }, // если 18+ разрешено
    { word: 'Пародировать Майкла Джексона', difficulty: 'hard', category: 'actions' },
    { word: 'Танцевать тверк', difficulty: 'hard', category: 'actions' },
    { word: 'Медитировать в позе лотоса', difficulty: 'hard', category: 'actions' },
    { word: 'Показывать пантомиму "я ем спагетти вилкой"', difficulty: 'hard', category: 'actions' }
    ],
    
    professions: [
{ word: 'Врач', difficulty: 'easy', category: 'professions' },
        { word: 'Учитель', difficulty: 'easy', category: 'professions' },
        { word: 'Полицейский', difficulty: 'easy', category: 'professions' },
        { word: 'Пожарный', difficulty: 'easy', category: 'professions' },
        { word: 'Повар', difficulty: 'easy', category: 'professions' },
        { word: 'Строитель', difficulty: 'medium', category: 'professions' },
        { word: 'Программист', difficulty: 'medium', category: 'professions' },
        { word: 'Дизайнер', difficulty: 'medium', category: 'professions' },
        { word: 'Журналист', difficulty: 'medium', category: 'professions' },
        { word: 'Актер', difficulty: 'medium', category: 'professions' },
        { word: 'Сантехник', difficulty: 'medium', category: 'professions' },
        { word: 'Электрик', difficulty: 'medium', category: 'professions' },
        { word: 'Водитель', difficulty: 'easy', category: 'professions' },
        { word: 'Пилот', difficulty: 'medium', category: 'professions' },
        { word: 'Космонавт', difficulty: 'medium', category: 'professions' },
        { word: 'Бухгалтер', difficulty: 'medium', category: 'professions' },
        { word: 'Юрист', difficulty: 'medium', category: 'professions' },
        { word: 'Стриптизёр', difficulty: 'medium', category: 'professions' },
        { word: 'Акушерка', difficulty: 'medium', category: 'professions' },
        { word: 'Ветеринар', difficulty: 'medium', category: 'professions' },
        { word: 'Стоматолог', difficulty: 'hard', category: 'professions' },
    { word: 'Гинеколог', difficulty: 'hard', category: 'professions' },
    { word: 'Проктолог', difficulty: 'hard', category: 'professions' },
    { word: 'Венеролог', difficulty: 'hard', category: 'professions' },
    { word: 'Анестезиолог', difficulty: 'hard', category: 'professions' },
    { word: 'Нейрохирург', difficulty: 'hard', category: 'professions' },
    { word: 'Криптограф', difficulty: 'hard', category: 'professions' },
    { word: 'Актуарий', difficulty: 'hard', category: 'professions' },
    { word: 'Сомелье', difficulty: 'hard', category: 'professions' },
    { word: 'Таксидермист', difficulty: 'hard', category: 'professions' }
    ],
    
    movies: [
{ word: 'Титаник', difficulty: 'easy', category: 'movies' },
        { word: 'Гарри Поттер', difficulty: 'easy', category: 'movies' },
        { word: 'Властелин колец', difficulty: 'easy', category: 'movies' },
        { word: 'Звездные войны', difficulty: 'easy', category: 'movies' },
        { word: 'Король Лев', difficulty: 'easy', category: 'movies' },
        { word: 'Интерстеллар', difficulty: 'medium', category: 'movies' },
        { word: 'Начало', difficulty: 'medium', category: 'movies' },
        { word: 'Побег из Шоушенка', difficulty: 'medium', category: 'movies' },
        { word: 'Криминальное чтиво', difficulty: 'medium', category: 'movies' },
        { word: 'Игра престолов', difficulty: 'medium', category: 'movies' },
        { word: 'Матрица', difficulty: 'medium', category: 'movies' },
        { word: 'Аватар', difficulty: 'easy', category: 'movies' },
        { word: 'Джентльмены', difficulty: 'medium', category: 'movies' },
        { word: 'Оппенгеймер', difficulty: 'medium', category: 'movies' },
        { word: 'Очень страшное кино', difficulty: 'hard', category: 'movies' },
    { word: 'Молчание ягнят', difficulty: 'hard', category: 'movies' },
    { word: 'Бойцовский клуб', difficulty: 'hard', category: 'movies' },
    { word: 'Семь', difficulty: 'hard', category: 'movies' },
    { word: 'Олдбой', difficulty: 'hard', category: 'movies' },
    { word: 'Мemento', difficulty: 'hard', category: 'movies' },
    { word: 'Город грехов', difficulty: 'hard', category: 'movies' }
    ],
    
    celebrities: [
        { word: 'Путин', difficulty: 'easy', category: 'celebrities' },
        { word: 'Эйнштейн', difficulty: 'easy', category: 'celebrities' },
        { word: 'Моцарт', difficulty: 'easy', category: 'celebrities' },
        { word: 'Леонардо да Винчи', difficulty: 'medium', category: 'celebrities' },
        { word: 'Мерлин Монро', difficulty: 'medium', category: 'celebrities' },
        { word: 'Майкл Джексон', difficulty: 'medium', category: 'celebrities' },
        { word: 'Билл Гейтс', difficulty: 'medium', category: 'celebrities' },
        { word: 'Илон Маск', difficulty: 'medium', category: 'celebrities' },
        { word: 'Стив Джобс', difficulty: 'medium', category: 'celebrities' },
        { word: 'Ким Кардашьян', difficulty: 'medium', category: 'celebrities' },
        { word: 'Юра Борисов', difficulty: 'medium', category: 'celebrities' },
        { word: 'Никола Тесла', difficulty: 'hard', category: 'celebrities' },
    { word: 'Стивен Хокинг', difficulty: 'hard', category: 'celebrities' },
    { word: 'Альберт Эйнштейн', difficulty: 'hard', category: 'celebrities' }, // уже был easy, можно поднять
    { word: 'Фридрих Ницше', difficulty: 'hard', category: 'celebrities' },
    { word: 'Зигмунд Фрейд', difficulty: 'hard', category: 'celebrities' }
    ],
    
    food: [
{ word: 'Яблоко', difficulty: 'easy', category: 'food' },
        { word: 'Банан', difficulty: 'easy', category: 'food' },
        { word: 'Пицца', difficulty: 'easy', category: 'food' },
        { word: 'Бургер', difficulty: 'easy', category: 'food' },
        { word: 'Мороженое', difficulty: 'easy', category: 'food' },
        { word: 'Шоколад', difficulty: 'easy', category: 'food' },
        { word: 'Спагетти', difficulty: 'medium', category: 'food' },
        { word: 'Суши', difficulty: 'medium', category: 'food' },
        { word: 'Кебаб', difficulty: 'medium', category: 'food' },
        { word: 'Борщ', difficulty: 'medium', category: 'food' },
        { word: 'Шашлык', difficulty: 'medium', category: 'food' },
        { word: 'Пельмени', difficulty: 'medium', category: 'food' },
        { word: 'Салат', difficulty: 'easy', category: 'food' },
        { word: 'Суп', difficulty: 'easy', category: 'food' },
        { word: 'Торт', difficulty: 'easy', category: 'food' },
        { word: 'Чипсы', difficulty: 'easy', category: 'food' },
        { word: 'Попкорн', difficulty: 'easy', category: 'food' },
        { word: 'Фуа-гра', difficulty: 'hard', category: 'food' },
    { word: 'Тартар', difficulty: 'hard', category: 'food' },
    { word: 'Карпаччо', difficulty: 'hard', category: 'food' },
    { word: 'Эскарго', difficulty: 'hard', category: 'food' },
    { word: 'Крокембуш', difficulty: 'hard', category: 'food' },
    { word: 'Макароны с трюфелем', difficulty: 'hard', category: 'food' }
    ],
    
    memnoe: [
{ word: 'Окак', difficulty: 'easy', category: 'memnoe' },
        { word: 'Дикий огурец', difficulty: 'easy', category: 'memnoe' },
        { word: 'Брейнрот', difficulty: 'medium', category: 'memnoe' },
        { word: 'Тралалео Тралала', difficulty: 'medium', category: 'memnoe' },
        { word: 'Лабубу', difficulty: 'easy', category: 'memnoe' },
        { word: 'Итальянский брейнрот', difficulty: 'medium', category: 'memnoe' },
        { word: 'А ниче тот факт что', difficulty: 'medium', category: 'memnoe' },
        { word: 'Смерть в нищете покой в роскоши', difficulty: 'hard', category: 'memnoe' },
        { word: 'Эффект Долиной', difficulty: 'medium', category: 'memnoe' },
        { word: 'Сам решу', difficulty: 'easy', category: 'memnoe' },
        { word: 'Умный человек в очках', difficulty: 'medium', category: 'memnoe' },
        { word: 'Сидим с бобром за столом', difficulty: 'medium', category: 'memnoe' },
        { word: 'Сияй Мага', difficulty: 'medium', category: 'memnoe' },
        { word: 'Птица марбау', difficulty: 'easy', category: 'memnoe' },
        { word: 'Тёрли свинки друг другу спинки', difficulty: 'medium', category: 'memnoe' },
        { word: 'Злой крокодил', difficulty: 'easy', category: 'memnoe' },
        { word: 'Страшный гусь', difficulty: 'easy', category: 'memnoe' },
        { word: 'Енот-полоскун', difficulty: 'medium', category: 'memnoe' },
        { word: 'Винни Пух похудел', difficulty: 'medium', category: 'memnoe' },
        { word: 'Чупакабра', difficulty: 'medium', category: 'memnoe' }
    ],
    
    18+: [
{ word: 'Поцелуй', difficulty: 'easy', category: '18+' },
        { word: 'Флирт', difficulty: 'easy', category: '18+' },
        { word: 'Стриптиз', difficulty: 'easy', category: '18+' },
        { word: 'Оргазм', difficulty: 'medium', category: '18+' },
        { word: 'Мастурбация', difficulty: 'medium', category: '18+' },
        { word: 'Секс', difficulty: 'medium', category: '18+' },
        { word: 'Презерватив', difficulty: 'medium', category: '18+' },
        { word: 'Эрекция', difficulty: 'medium', category: '18+' },
        { word: 'Минет', difficulty: 'hard', category: '18+' },
        { word: 'Кунилингус', difficulty: 'hard', category: '18+' },
        { word: 'БДСМ', difficulty: 'hard', category: '18+' },
        { word: 'Свингеры', difficulty: 'hard', category: '18+' },
        { word: 'Порнуха', difficulty: 'hard', category: '18+' },
        { word: 'Дилдо', difficulty: 'medium', category: '18+' },
        { word: 'Вибратор', difficulty: 'medium', category: '18+' },
        { word: 'Ролевые игры', difficulty: 'medium', category: '18+' },
        { word: 'Тройничок', difficulty: 'hard', category: '18+' },
        { word: 'Золотой дождь', difficulty: 'hard', category: '18+' },
        { word: 'Фистинг', difficulty: 'hard', category: '18+' },
        { word: 'Камасутра', difficulty: 'medium', category: '18+' },
        { word: 'Либидо', difficulty: 'medium', category: '18+' },
        { word: 'Возбуждение', difficulty: 'easy', category: '18+' },
        { word: 'Стриптизёрша', difficulty: 'medium', category: '18+' },
        { word: 'Золотой дождь', difficulty: 'hard', category: '18+' },
    { word: 'Фистинг', difficulty: 'hard', category: '18+' },
    { word: 'Пеггинг', difficulty: 'hard', category: '18+' },
    { word: 'Буккакэ', difficulty: 'hard', category: '18+' },
    { word: 'Сквирт', difficulty: 'hard', category: '18+' },
    { word: 'Копрофилия', difficulty: 'hard', category: '18+' },
    { word: 'Садомазохизм', difficulty: 'hard', category: '18+' }
    ]
};

