// ===== ОБЪЕДИНЕННАЯ БАЗА СЛОВ ДЛЯ КРОКОДИЛА И АЛИАСА =====

const gameWords = {
    // Категории из Крокодила
    objects: [
        { word: 'Телефон', category: 'objects' },
        { word: 'Книга', category: 'objects' },
        { word: 'Стул', category: 'objects' },
        { word: 'Лампа', category: 'objects' },
        { word: 'Часы', category: 'objects' },
        { word: 'Очки', category: 'objects' },
        { word: 'Ключи', category: 'objects' },
        { word: 'Рюкзак', category: 'objects' },
        { word: 'Зонт', category: 'objects' },
        { word: 'Микрофон', category: 'objects' },
        { word: 'Ноутбук', category: 'objects' },
        { word: 'Холодильник', category: 'objects' },
        { word: 'Телевизор', category: 'objects' },
        { word: 'Кровать', category: 'objects' },
        { word: 'Зеркало', category: 'objects' },
        { word: 'Вилка', category: 'objects' },
        { word: 'Ложка', category: 'objects' },
        { word: 'Нож', category: 'objects' },
        { word: 'Тарелка', category: 'objects' },
        { word: 'Чашка', category: 'objects' },
        { word: 'Молоток', category: 'objects' },
        { word: 'Отвёртка', category: 'objects' },
        { word: 'Пила', category: 'objects' },
        { word: 'Дрель', category: 'objects' },
        { word: 'Наушники', category: 'objects' },
        { word: 'Планшет', category: 'objects' },
        { word: 'Калькулятор', category: 'objects' },
        { word: 'Флешка', category: 'objects' },
        { word: 'Клавиатура', category: 'objects' },
        { word: 'Мышь', category: 'objects' },
        { word: 'Утюг', category: 'objects' },
        { word: 'Стиральная машина', category: 'objects' },
        { word: 'Пылесос', category: 'objects' },
        { word: 'Батарейка', category: 'objects' },
        { word: 'Лампочка', category: 'objects' },
        { word: 'Кубик Рубика', category: 'objects' },
        { word: 'Гитара', category: 'objects' },
        { word: 'Пианино', category: 'objects' },
        { word: 'Барабан', category: 'objects' },
        { word: 'Шарф', category: 'objects' },
        { word: 'Шапка', category: 'objects' },
        { word: 'Перчатки', category: 'objects' },
        { word: 'Ремень', category: 'objects' },
        { word: 'Галстук', category: 'objects' },
        { word: 'Кошелёк', category: 'objects' },
        { word: 'Сумочка', category: 'objects' },
        { word: 'Бинокль', category: 'objects' },
        { word: 'Компас', category: 'objects' },
        { word: 'Термос', category: 'objects' },
        { word: 'Фонарик', category: 'objects' },
        { word: 'Ножницы', category: 'objects' },
        { word: 'Линейка', category: 'objects' },
        { word: 'Скотч', category: 'objects' },
        { word: 'Клей', category: 'objects' },
        { word: 'Кран', category: 'objects' },
        { word: 'Дверь', category: 'objects' },
        { word: 'Окно', category: 'objects' },
        { word: 'Ковёр', category: 'objects' },
        { word: 'Штора', category: 'objects' },
        { word: 'Ваза', category: 'objects' },
        { word: 'Картина', category: 'objects' },
        { word: 'Рамка', category: 'objects' },
        { word: 'Будильник', category: 'objects' },
        { word: 'Зарядка', category: 'objects' },
        { word: 'Акварель', category: 'objects' },
        { word: 'Оригами', category: 'objects' },
        { word: 'Матрёшка', category: 'objects' },
        { word: 'Хот-дог', category: 'objects' },
        { word: 'Микроволновая печь', category: 'objects' },
        { word: 'Электрочайник', category: 'objects' },
        { word: 'Кофеварка', category: 'objects' },
        { word: 'Блендер', category: 'objects' },
        { word: 'Тостер', category: 'objects' },
        { word: 'Мультиварка', category: 'objects' },
        { word: 'Пароочиститель', category: 'objects' },
        { word: 'Секундомер', category: 'objects' },
        { word: 'Термометр', category: 'objects' },
        { word: 'Манекен', category: 'objects' },
        { word: 'Калейдоскоп', category: 'objects' },
        { word: 'Телескоп', category: 'objects' },
        { word: 'Микроскоп', category: 'objects' }
    ],
    
    animals: [
        { word: 'Кошка', category: 'animals' },
        { word: 'Собака', category: 'animals' },
        { word: 'Лошадь', category: 'animals' },
        { word: 'Корова', category: 'animals' },
        { word: 'Слон', category: 'animals' },
        { word: 'Лев', category: 'animals' },
        { word: 'Пингвин', category: 'animals' },
        { word: 'Кенгуру', category: 'animals' },
        { word: 'Дельфин', category: 'animals' },
        { word: 'Бегемот', category: 'animals' },
        { word: 'Жираф', category: 'animals' },
        { word: 'Зебра', category: 'animals' },
        { word: 'Обезьяна', category: 'animals' },
        { word: 'Медведь', category: 'animals' },
        { word: 'Волк', category: 'animals' },
        { word: 'Лиса', category: 'animals' },
        { word: 'Енот', category: 'animals' },
        { word: 'Осьминог', category: 'animals' },
        { word: 'Акула', category: 'animals' },
        { word: 'Кит', category: 'animals' },
        { word: 'Панда', category: 'animals' },
        { word: 'Тигр', category: 'animals' },
        { word: 'Крокодил', category: 'animals' },
        { word: 'Страус', category: 'animals' },
        { word: 'Павлин', category: 'animals' },
        { word: 'Попугай', category: 'animals' },
        { word: 'Хамелеон', category: 'animals' },
        { word: 'Улитка', category: 'animals' },
        { word: 'Паук', category: 'animals' },
        { word: 'Бабочка', category: 'animals' },
        { word: 'Платипус', category: 'animals' },
        { word: 'Ехидна', category: 'animals' },
        { word: 'Аксолотль', category: 'animals' },
        { word: 'Нарвал', category: 'animals' },
        { word: 'Тарсиер', category: 'animals' },
        { word: 'Манул', category: 'animals' },
        { word: 'Окапи', category: 'animals' },
        { word: 'Фенек', category: 'animals' },
        { word: 'Ленивец', category: 'animals' },
        { word: 'Муравьед', category: 'animals' },
        { word: 'Броненосец', category: 'animals' },
        { word: 'Капибара', category: 'animals' }
    ],
    
    actions: [
        { word: 'Бегать', category: 'actions' },
        { word: 'Прыгать', category: 'actions' },
        { word: 'Плавать', category: 'actions' },
        { word: 'Танцевать', category: 'actions' },
        { word: 'Спать', category: 'actions' },
        { word: 'Есть', category: 'actions' },
        { word: 'Пить', category: 'actions' },
        { word: 'Готовить', category: 'actions' },
        { word: 'Водить машину', category: 'actions' },
        { word: 'Читать', category: 'actions' },
        { word: 'Петь', category: 'actions' },
        { word: 'Рисовать', category: 'actions' },
        { word: 'Писать', category: 'actions' },
        { word: 'Смеяться', category: 'actions' },
        { word: 'Плакать', category: 'actions' },
        { word: 'Обнимать', category: 'actions' },
        { word: 'Целовать', category: 'actions' },
        { word: 'Бить', category: 'actions' },
        { word: 'Летать', category: 'actions' },
        { word: 'Копать', category: 'actions' },
        { word: 'Рыбачить', category: 'actions' },
        { word: 'Кататься на лыжах', category: 'actions' },
        { word: 'Йога', category: 'actions' },
        { word: 'Селфи делать', category: 'actions' },
        { word: 'Зевать', category: 'actions' },
        { word: 'Чихать', category: 'actions' },
        { word: 'Кашлять', category: 'actions' },
        { word: 'Жонглировать тремя мячами', category: 'actions' },
        { word: 'Делать сальто назад', category: 'actions' },
        { word: 'Медитировать в позе лотоса', category: 'actions' }
    ],
    
    professions: [
        { word: 'Врач', category: 'professions' },
        { word: 'Учитель', category: 'professions' },
        { word: 'Полицейский', category: 'professions' },
        { word: 'Пожарный', category: 'professions' },
        { word: 'Повар', category: 'professions' },
        { word: 'Строитель', category: 'professions' },
        { word: 'Программист', category: 'professions' },
        { word: 'Дизайнер', category: 'professions' },
        { word: 'Журналист', category: 'professions' },
        { word: 'Актер', category: 'professions' },
        { word: 'Сантехник', category: 'professions' },
        { word: 'Электрик', category: 'professions' },
        { word: 'Водитель', category: 'professions' },
        { word: 'Пилот', category: 'professions' },
        { word: 'Космонавт', category: 'professions' },
        { word: 'Бухгалтер', category: 'professions' },
        { word: 'Юрист', category: 'professions' },
        { word: 'Ветеринар', category: 'professions' },
        { word: 'Стоматолог', category: 'professions' },
        { word: 'Нейрохирург', category: 'professions' },
        { word: 'Криптограф', category: 'professions' },
        { word: 'Сомелье', category: 'professions' }
    ],
    
    movies: [
        { word: 'Титаник', category: 'movies' },
        { word: 'Гарри Поттер', category: 'movies' },
        { word: 'Властелин колец', category: 'movies' },
        { word: 'Звездные войны', category: 'movies' },
        { word: 'Король Лев', category: 'movies' },
        { word: 'Интерстеллар', category: 'movies' },
        { word: 'Начало', category: 'movies' },
        { word: 'Побег из Шоушенка', category: 'movies' },
        { word: 'Криминальное чтиво', category: 'movies' },
        { word: 'Игра престолов', category: 'movies' },
        { word: 'Матрица', category: 'movies' },
        { word: 'Аватар', category: 'movies' },
        { word: 'Джентльмены', category: 'movies' },
        { word: 'Очень страшное кино', category: 'movies' },
        { word: 'Бойцовский клуб', category: 'movies' },
        { word: 'Семь', category: 'movies' }
    ],
    
    celebrities: [
        { word: 'Путин', category: 'celebrities' },
        { word: 'Эйнштейн', category: 'celebrities' },
        { word: 'Моцарт', category: 'celebrities' },
        { word: 'Леонардо да Винчи', category: 'celebrities' },
        { word: 'Мерлин Монро', category: 'celebrities' },
        { word: 'Майкл Джексон', category: 'celebrities' },
        { word: 'Билл Гейтс', category: 'celebrities' },
        { word: 'Илон Маск', category: 'celebrities' },
        { word: 'Стив Джобс', category: 'celebrities' },
        { word: 'Ким Кардашьян', category: 'celebrities' },
        { word: 'Никола Тесла', category: 'celebrities' },
        { word: 'Стивен Хокинг', category: 'celebrities' },
        { word: 'Зигмунд Фрейд', category: 'celebrities' }
    ],
    
    food: [
        { word: 'Яблоко', category: 'food' },
        { word: 'Банан', category: 'food' },
        { word: 'Пицца', category: 'food' },
        { word: 'Бургер', category: 'food' },
        { word: 'Мороженое', category: 'food' },
        { word: 'Шоколад', category: 'food' },
        { word: 'Спагетти', category: 'food' },
        { word: 'Суши', category: 'food' },
        { word: 'Кебаб', category: 'food' },
        { word: 'Борщ', category: 'food' },
        { word: 'Шашлык', category: 'food' },
        { word: 'Пельмени', category: 'food' },
        { word: 'Салат', category: 'food' },
        { word: 'Суп', category: 'food' },
        { word: 'Торт', category: 'food' },
        { word: 'Чипсы', category: 'food' },
        { word: 'Попкорн', category: 'food' },
        { word: 'Фуа-гра', category: 'food' },
        { word: 'Карпаччо', category: 'food' },
        { word: 'Эскарго', category: 'food' }
    ],
    
    memnoe: [
        { word: 'Окак', category: 'memnoe' },
        { word: 'Дикий огурец', category: 'memnoe' },
        { word: 'Брейнрот', category: 'memnoe' },
        { word: 'Тралалео Тралала', category: 'memnoe' },
        { word: 'Лабубу', category: 'memnoe' },
        { word: 'Итальянский брейнрот', category: 'memnoe' },
        { word: 'А ниче тот факт что', category: 'memnoe' },
        { word: 'Смерть в нищете покой в роскоши', category: 'memnoe' },
        { word: 'Эффект Долиной', category: 'memnoe' },
        { word: 'Сам решу', category: 'memnoe' },
        { word: 'Умный человек в очках', category: 'memnoe' },
        { word: 'Сидим с бобром за столом', category: 'memnoe' },
        { word: 'Сияй Мага', category: 'memnoe' },
        { word: 'Птица марбау', category: 'memnoe' },
        { word: 'Тёрли свинки друг другу спинки', category: 'memnoe' },
        { word: 'Злой крокодил', category: 'memnoe' },
        { word: 'Страшный гусь', category: 'memnoe' },
        { word: 'Енот-полоскун', category: 'memnoe' },
        { word: 'Винни Пух похудел', category: 'memnoe' },
        { word: 'Чупакабра', category: 'memnoe' }
    ],
    
    adult: [
        { word: 'Поцелуй', category: 'adult' },
        { word: 'Флирт', category: 'adult' },
        { word: 'Стриптиз', category: 'adult' },
        { word: 'Секс', category: 'adult' },
        { word: 'Презерватив', category: 'adult' },
        { word: 'Ролевые игры', category: 'adult' },
        { word: 'Камасутра', category: 'adult' },
        { word: 'Возбуждение', category: 'adult' }
    ],
    
    // Новые категории из Алиаса
    technology: [
        { word: 'Компьютер', category: 'technology' },
        { word: 'Смартфон', category: 'technology' },
        { word: 'Интернет', category: 'technology' },
        { word: 'Wi-Fi', category: 'technology' },
        { word: 'Блютуз', category: 'technology' },
        { word: 'Робот', category: 'technology' },
        { word: 'Искусственный интеллект', category: 'technology' },
        { word: 'Виртуальная реальность', category: 'technology' },
        { word: 'Криптовалюта', category: 'technology' },
        { word: 'Приложение', category: 'technology' },
        { word: 'Сайт', category: 'technology' },
        { word: 'Планшет', category: 'technology' },
        { word: 'Ноутбук', category: 'technology' },
        { word: 'Наушники', category: 'technology' },
        { word: 'Колонки', category: 'technology' },
        { word: 'Микрофон', category: 'technology' },
        { word: 'Камера', category: 'technology' },
        { word: 'Дрон', category: 'technology' }
    ],
    
    emotions: [
        { word: 'Счастье', category: 'emotions' },
        { word: 'Радость', category: 'emotions' },
        { word: 'Любовь', category: 'emotions' },
        { word: 'Удивление', category: 'emotions' },
        { word: 'Злость', category: 'emotions' },
        { word: 'Грусть', category: 'emotions' },
        { word: 'Страх', category: 'emotions' },
        { word: 'Волнение', category: 'emotions' },
        { word: 'Спокойствие', category: 'emotions' },
        { word: 'Гордость', category: 'emotions' },
        { word: 'Стыд', category: 'emotions' },
        { word: 'Ревность', category: 'emotions' },
        { word: 'Зависть', category: 'emotions' },
        { word: 'Надежда', category: 'emotions' },
        { word: 'Разочарование', category: 'emotions' }
    ],
    
    countries: [
        { word: 'Россия', category: 'countries' },
        { word: 'США', category: 'countries' },
        { word: 'Китай', category: 'countries' },
        { word: 'Япония', category: 'countries' },
        { word: 'Германия', category: 'countries' },
        { word: 'Франция', category: 'countries' },
        { word: 'Италия', category: 'countries' },
        { word: 'Испания', category: 'countries' },
        { word: 'Великобритания', category: 'countries' },
        { word: 'Канада', category: 'countries' },
        { word: 'Австралия', category: 'countries' },
        { word: 'Бразилия', category: 'countries' },
        { word: 'Мексика', category: 'countries' },
        { word: 'Индия', category: 'countries' },
        { word: 'Египет', category: 'countries' }
    ],
    
    cities: [
        { word: 'Москва', category: 'cities' },
        { word: 'Санкт-Петербург', category: 'cities' },
        { word: 'Лондон', category: 'cities' },
        { word: 'Париж', category: 'cities' },
        { word: 'Нью-Йорк', category: 'cities' },
        { word: 'Токио', category: 'cities' },
        { word: 'Пекин', category: 'cities' },
        { word: 'Берлин', category: 'cities' },
        { word: 'Рим', category: 'cities' },
        { word: 'Мадрид', category: 'cities' },
        { word: 'Сидней', category: 'cities' },
        { word: 'Дубай', category: 'cities' },
        { word: 'Стамбул', category: 'cities' },
        { word: 'Венеция', category: 'cities' },
        { word: 'Амстердам', category: 'cities' }
    ],
    
    music: [
        { word: 'Гитара', category: 'music' },
        { word: 'Пианино', category: 'music' },
        { word: 'Скрипка', category: 'music' },
        { word: 'Барабаны', category: 'music' },
        { word: 'Флейта', category: 'music' },
        { word: 'Саксофон', category: 'music' },
        { word: 'Труба', category: 'music' },
        { word: 'Песня', category: 'music' },
        { word: 'Певица', category: 'music' },
        { word: 'Певец', category: 'music' },
        { word: 'Группа', category: 'music' },
        { word: 'Концерт', category: 'music' },
        { word: 'Дискотека', category: 'music' },
        { word: 'Рэп', category: 'music' },
        { word: 'Рок', category: 'music' },
        { word: 'Поп', category: 'music' },
        { word: 'Джаз', category: 'music' },
        { word: 'Классика', category: 'music' }
    ],
    
    nature: [
        { word: 'Солнце', category: 'nature' },
        { word: 'Луна', category: 'nature' },
        { word: 'Звезды', category: 'nature' },
        { word: 'Облака', category: 'nature' },
        { word: 'Дождь', category: 'nature' },
        { word: 'Снег', category: 'nature' },
        { word: 'Радуга', category: 'nature' },
        { word: 'Гроза', category: 'nature' },
        { word: 'Вулкан', category: 'nature' },
        { word: 'Водопад', category: 'nature' },
        { word: 'Река', category: 'nature' },
        { word: 'Озеро', category: 'nature' },
        { word: 'Остров', category: 'nature' },
        { word: 'Цветок', category: 'nature' },
        { word: 'Дерево', category: 'nature' }
    ]
};

// Все слова для быстрого доступа
const allWords = [];
for (const category in gameWords) {
    gameWords[category].forEach(wordObj => {
        allWords.push(wordObj);
    });
}